version: '3.8'
services:
  rabbitmq1:
    image: rabbitmq:4.1.0-management
    container_name: rabbitmq1
    hostname: rabbitmq1
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    volumes:
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: ["sh", "/usr/local/bin/cluster-entrypoint.sh"]

  rabbitmq2:
    image: rabbitmq:4.1.0-management
    container_name: rabbitmq2
    hostname: rabbitmq2
    depends_on:
      - rabbitmq1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
    ports:
      - "5673:5672"
      - "15673:15672"
      - "15693:15692"
    volumes:
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: ["sh", "/usr/local/bin/cluster-entrypoint.sh"]

  rabbitmq3:
    image: rabbitmq:4.1.0-management
    container_name: rabbitmq3
    hostname: rabbitmq3
    depends_on:
      - rabbitmq1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
    ports:
      - "5674:5672"
      - "15674:15672"
      - "15694:15692"
    volumes:
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: ["sh", "/usr/local/bin/cluster-entrypoint.sh"]